### ISSUE TITLE
Lab 3 submission

### ISSUE THREAD

**Issue by TarekCodes** [cisc3620/3-animate-drawing#1]
Do we need to fork the repository? The link in the schedule only takes us to the repository itself, it doesn't create it automatically for us.

**Comment by rivlev** [comment]
Try again, it should take you to the github classroom link and create the repository for you.

**Comment by TarekCodes** [comment]
Still not working. The lab 3 link on the website is just a regular Github link, not a GithubClassroom link.

**Comment by rivlev** [comment]
Fixed, thanks. It may take a couple of minutes to update.
