### ISSUE TITLE
Need help animating in the rendering loop

### ISSUE THREAD

**Issue by Emmgreens** [cisc3620/3-animate-drawing#2]
@rivlev

I modified the transformation, but am not sure how to make it move like an animation in the rendering loop.
Thank you!

**Comment by rivlev** [comment]
Create a new version of the model matrix on each iteration of the rendering loop. For example, you could have a parameter t that starts off as -0.5, and then inside the loop you could have t = -t. Also inside the loop, you do ```model = glm::translate(glm::mat4(1.0f), glm::vec3(t, t, 0)));``` This will move the shape back and forth.
