### ISSUE TITLE
How transformation works

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/3-animate-drawing#3]
@rivlev In class i believe you mentioned that to make these transformations we are going to be sending matrixes, and the order has to be translate, rotate, scale, and looking at the slides i can see why each type of matrix performs that type of transformation.  I believe you mentioned that one of the ways to do this would be to multiply the matrices in the correct order.  I think that in order to do this, that i would start with adding to the model transformation matrix, where i can see it is already set up to scale. But i am not seeing any four by four matrices in main so maybe i am wrong. What would be the best first step in figuring out what changes to make to main to modify the transformation?

**Comment by rivlev** [comment]
glm::scale returns a glm::mat4 which is a 4 by 4 matrix. The other glm transformation methods return other 4x4 matrices.

**Comment by MichaelGregg** [comment]
in order to create the translation matrixes for translation and rotation, i am trying:
![screen shot 2017-02-19 at 5 50 16 pm](https://cloud.githubusercontent.com/assets/25493211/23107475/eb3e8f8c-f6cb-11e6-9c8c-f9addc6a46f6.png)

A.)When the scale_model is established, the first parameter in glm::scale is glm::mat4(1.0f) This is the identity matrix.  Why is this the first parameter?  The second parameter is glm::vec3(0.5f,0.5f,0.0f) is this a vector specifying that the shape shall be scaled by 0.5 on the x-axis, 0.5 on the y-axis, and 0.0 on the z-axis? Is the first parameter for both the rotate_model and the translate_model going to the the identity matrix as well? and is the second parameter of both the translate_model and rotate_model going to be a 3-element vector specifying the degree of transformation on the x, y and z axis respectively?   Because opengl-tutorial.org which is the best documentation with code that i can find instructs that the parameters for translate and scale model matrixes are 3 floats, each specifying the degree of change on the x, y and z axes, and the tutorial instructs that the first two parameters of the rotate matrix are supposed to be the angle in degrees, and a vector specifying the rotation point, but doing it the way that the tutorial instructs returns an error as well 
  
B.) What does this command do?
glm::mat4 model = scale_model;

**Comment by MichaelGregg** [comment]
Changing the first parameter of the rotation model to a float solved the error but i am still not sure if i have established the transformation matrices correctly:
![screen shot 2017-02-19 at 6 11 47 pm](https://cloud.githubusercontent.com/assets/25493211/23107655/ebc5ea42-f6ce-11e6-9bb3-fae57c78b4f4.png)
Is the matrix called 'model' for the purpose of creating a matrix that cumulates the transformations
as i tried to do with it on the bottom line of the image?

**Comment by rivlev** [comment]
Yes, that looks good.

**Comment by MichaelGregg** [comment]
I moved on to the next step which is moving the lines on 123 and 124 inside the rendering loop, which i did.  Also in order to animate the shape i took the advice given in the other issue raised for this assignment, trying to modify the matrix inside the rendering loop by creating a variable named t in the model matrix, and setting t=-t in the rendering loop.  But the only output at this point is the window with the pink, background- no triangle.  I am not sure if i made a mistake or am missing a step:
![screen shot 2017-02-20 at 4 05 14 pm](https://cloud.githubusercontent.com/assets/25493211/23141776/6f44b102-f786-11e6-94e7-67aee9813e31.png)

**Comment by rivlev** [comment]
You are not modifying the models inside the loop,  you are just multiplying them together again and again.
