### ISSUE TITLE
glfw3.dll is missing

### ISSUE THREAD

**Issue by SIRGHST** [cisc3620/3-animate-drawing#5]
Keep getting this message when I run my program.Why is that?

![screenshot 5](https://cloud.githubusercontent.com/assets/7463854/23197021/66b11c6e-f88b-11e6-8d21-a69dfc928df0.png)

@rivlev

**Comment by SIRGHST** [comment]
nvm,I got it to work.I just deleted the cache and reconfigured in cmake

**Comment by rivlev** [comment]
What did you need to reconfigure? @SIRGHST

**Comment by SIRGHST** [comment]
I got it to work,I logged out of VS and logged back in and everything worked fine
